#!/bin/bash -e

function output_cmd () {
    local arg=( `echo $1 | tr -s ':' ' '`)
    if [ ${#arg[@]} -ne 2 ]; then
        echo 'argument format is not correct!' 1>&2
        echo 'format="container_name:command_path"' 1>&2
        exit 1
    fi
    local container_name=${arg[0]}
    local command_path=${arg[1]}
    local command_name=`basename ${arg[1]}`
    echo 'docker exec -i --workdir $(pwd) '"${container_name} ${command_path}"' "$@"' > ~/.local/bin/${command_name}
    chmod +x ~/.local/bin/${command_name}
}

if [ $# -eq 0 ]; then
    echo 'no arguments is specified!' 1>&2
    script_name=${0##*/}
    echo 'usage="'"${script_name}"' container_name1:command_path1 container_name2:command_path2 ..."' 1>&2
    exit 1
fi

args=$@
echo "arguments = ${args}"

index=0
for arg in ${args[@]}; do
    echo "arguments[${index}] = ${arg}"
    let ++index
    output_cmd ${arg}
done
