name: Docker Image CI

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*.*.*'

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Build and push
        uses: k-ishigaki/publish-docker-image-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
